name: dastardly-scan

on: 
  workflow_dispatch: {}
  schedule: ## Schedule the job to run at 12.am daily.
     - cron: '0/30 * * * *'
jobs:
  scheduled:

    runs-on: ubuntu-latest
    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true 
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://google-gruyere.appspot.com/'
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'
          require_Tests: true
permissions:
    contents: read
    issues: read
    checks: write
    pull-requests: write
    id-token: write
